"""
PDF Report Generation for Security Scans
Uses reportlab to generate professional PDF reports
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from datetime import datetime
import io


def generate_scan_report_pdf(scan_data, scan_type='file'):
    """
    Generate PDF report for scan results
    
    Args:
        scan_data: Dict containing scan results
        scan_type: 'file', 'email', 'url', or 'ip'
    
    Returns:
        BytesIO object containing PDF data
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                           rightMargin=72, leftMargin=72,
                           topMargin=72, bottomMargin=18)
    
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#2563eb'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=12,
        spaceBefore=12
    )
    
    # Title
    elements.append(Paragraph("SecureCheck Security Scan Report", title_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Report Info
    report_info = [
        ['Report Date:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
        ['Scan Type:', scan_type.upper()],
        ['Report ID:', f"RPT-{datetime.now().strftime('%Y%m%d%H%M%S')}"]
    ]
    
    info_table = Table(report_info, colWidths=[2*inch, 4*inch])
    info_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#374151')),
    ]))
    
    elements.append(info_table)
    elements.append(Spacer(1, 0.3*inch))
    
    # Add scan-specific content
    if scan_type == 'file':
        elements.extend(_generate_file_section(scan_data, styles, heading_style))
    elif scan_type == 'email':
        elements.extend(_generate_email_section(scan_data, styles, heading_style))
    elif scan_type == 'url':
        elements.extend(_generate_url_section(scan_data, styles, heading_style))
    elif scan_type == 'ip':
        elements.extend(_generate_ip_section(scan_data, styles, heading_style))
    
    # Footer
    elements.append(Spacer(1, 0.5*inch))
    elements.append(Paragraph(
        "<i>This report was automatically generated by SecureCheck AI-Powered Security Scanner</i>",
        styles['Normal']
    ))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer


def _generate_file_section(data, styles, heading_style):
    """Generate file scan content"""
    elements = []
    
    elements.append(Paragraph("Threat Assessment", heading_style))
    
    is_malicious = data.get('is_malicious', False)
    status_text = f"<font color='red'><b>MALICIOUS - {data.get('threat_level', 'HIGH')}</b></font>" if is_malicious else "<font color='green'><b>CLEAN</b></font>"
    
    elements.append(Paragraph(f"Status: {status_text}", styles['Normal']))
    elements.append(Spacer(1, 0.2*inch))
    
    # File Details
    elements.append(Paragraph("File Details", heading_style))
    
    file_details = [
        ['Filename:', data.get('filename', 'N/A')],
        ['File Size:', str(data.get('file_size', 'N/A'))],
        ['File Type:', data.get('file_type', 'N/A')],
        ['SHA-256 Hash:', data.get('file_hash', 'N/A')[:64]],
        ['Confidence Score:', f"{data.get('confidence_score', 0)}%"],
    ]
    
    if is_malicious:
        file_details.append(['Malware Type:', data.get('malware_type', 'Unknown')])
    
    details_table = Table(file_details, colWidths=[2*inch, 4*inch])
    details_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
    ]))
    
    elements.append(details_table)
    
    # ML Predictions
    if 'rf_prediction' in data:
        elements.append(Spacer(1, 0.2*inch))
        elements.append(Paragraph("ML Model Analysis", heading_style))
        
        ml_data = [
            ['Model', 'Prediction'],
            ['Random Forest', data.get('rf_prediction', 'N/A')],
            ['Decision Tree', data.get('dt_prediction', 'N/A')],
            ['SVM', data.get('svm_prediction', 'N/A')]
        ]
        
        ml_table = Table(ml_data, colWidths=[2*inch, 2*inch])
        ml_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563eb')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        
        elements.append(ml_table)
    
    return elements


def _generate_email_section(data, styles, heading_style):
    """Generate email scan content"""
    elements = []
    
    elements.append(Paragraph("Phishing Assessment", heading_style))
    
    is_phishing = data.get('is_phishing', False)
    score = data.get('phishing_score', 0)
    
    status_text = f"<font color='red'><b>PHISHING DETECTED ({score}%)</b></font>" if is_phishing else f"<font color='green'><b>SAFE ({100-score}% confidence)</b></font>"
    
    elements.append(Paragraph(f"Status: {status_text}", styles['Normal']))
    elements.append(Spacer(1, 0.2*inch))
    
    # Email Details
    elements.append(Paragraph("Email Information", heading_style))
    
    email_details = [
        ['From:', data.get('sender_email', 'N/A')],
        ['Subject:', data.get('subject', 'N/A')],
        ['Phishing Score:', f"{score}%"],
    ]
    
    details_table = Table(email_details, colWidths=[2*inch, 4*inch])
    details_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
    ]))
    
    elements.append(details_table)
    elements.append(Spacer(1, 0.2*inch))
    
    # Authentication
    elements.append(Paragraph("Authentication Checks", heading_style))
    
    auth_data = [
        ['Check', 'Result'],
        ['DKIM', data.get('dkim_status', 'None').upper()],
        ['SPF', data.get('spf_status', 'None').upper()],
        ['DMARC', data.get('dmarc_status', 'None').upper()]
    ]
    
    auth_table = Table(auth_data, colWidths=[2*inch, 2*inch])
    auth_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563eb')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    
    elements.append(auth_table)
    
    return elements


def _generate_url_section(data, styles, heading_style):
    """Generate URL scan content"""
    elements = []
    
    elements.append(Paragraph("URL Security Assessment", heading_style))
    
    threat_score = data.get('threat_score', 0)
    is_safe = threat_score < 30
    
    status_text = f"<font color='green'><b>SAFE</b></font>" if is_safe else f"<font color='red'><b>SUSPICIOUS ({threat_score}%)</b></font>"
    
    elements.append(Paragraph(f"Status: {status_text}", styles['Normal']))
    elements.append(Spacer(1, 0.2*inch))
    
    url_details = [
        ['URL:', data.get('url', 'N/A')],
        ['Threat Score:', f"{threat_score}%"],
        ['HTTPS:', 'Yes' if data.get('https', False) else 'No'],
    ]
    
    details_table = Table(url_details, colWidths=[2*inch, 4*inch])
    details_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
    ]))
    
    elements.append(details_table)
    
    return elements


def _generate_ip_section(data, styles, heading_style):
    """Generate IP scan content"""
    elements = []
    
    elements.append(Paragraph("IP Reputation Analysis", heading_style))
    
    abuse_score = data.get('abuse_score', 0)
    is_clean = abuse_score < 25
    
    status_text = f"<font color='green'><b>CLEAN</b></font>" if is_clean else f"<font color='red'><b>SUSPICIOUS ({abuse_score}%)</b></font>"
    
    elements.append(Paragraph(f"Status: {status_text}", styles['Normal']))
    elements.append(Spacer(1, 0.2*inch))
    
    ip_details = [
        ['IP Address:', data.get('ip_address', 'N/A')],
        ['Abuse Score:', f"{abuse_score}/100"],
        ['Country:', data.get('country', 'Unknown')],
        ['ISP:', data.get('isp', 'Unknown')],
    ]
    
    details_table = Table(ip_details, colWidths=[2*inch, 4*inch])
    details_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
    ]))
    
    elements.append(details_table)
    
    return elements
